-- Ejecutar en Supabase > SQL Editor

create table if not exists public.phase_updates (
  id bigint generated by default as identity primary key,
  phase text not null,
  excel_row integer not null,
  activity text not null,
  percent numeric not null check (percent >= 0 and percent <= 100),
  updated_by text,
  updated_at timestamptz not null default now(),
  unique (phase, excel_row, activity)
);

create table if not exists public.weekly_history (
  id bigint generated by default as identity primary key,
  update_date date not null unique,
  general numeric not null,
  fase1 numeric not null,
  fase2 numeric not null,
  fase3 numeric not null,
  fase4 numeric not null,
  updated_by text,
  created_at timestamptz not null default now()
);
