-- SFCO211 · Supabase setup v39
-- Ejecutar en Supabase > SQL Editor. Es idempotente: no borra datos existentes.

create table if not exists public.phase_updates (
  id bigint generated by default as identity primary key,
  phase text not null,
  excel_row integer not null,
  activity text not null,
  percent numeric not null check (percent >= 0 and percent <= 100),
  updated_by text,
  updated_at timestamptz not null default now(),
  unique (phase, excel_row, activity)
);

create table if not exists public.weekly_history (
  id bigint generated by default as identity primary key,
  update_date date not null unique,
  general numeric not null,
  fase1 numeric not null,
  fase2 numeric not null,
  fase3 numeric not null,
  fase4 numeric not null,
  updated_by text,
  created_at timestamptz not null default now()
);

-- Historial inmutable de cada modificación desde v39.
create table if not exists public.phase_update_history (
  id bigint generated by default as identity primary key,
  phase text not null,
  excel_row integer not null,
  activity text not null,
  old_percent numeric,
  new_percent numeric not null check (new_percent >= 0 and new_percent <= 100),
  changed_by text,
  changed_at timestamptz not null default now()
);
create index if not exists idx_phase_update_history_changed_at
  on public.phase_update_history(changed_at desc);
create index if not exists idx_phase_update_history_cell
  on public.phase_update_history(phase, excel_row, activity);

-- Fotografía detallada asociada a cada corte semanal desde v39.
create table if not exists public.weekly_detail_history (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  phase text not null,
  excel_row integer not null,
  activity text not null,
  percent numeric not null check (percent >= 0 and percent <= 100),
  captured_by text,
  captured_at timestamptz not null default now()
);
create index if not exists idx_weekly_detail_snapshot
  on public.weekly_detail_history(snapshot_date, phase, excel_row);
